spring.application.name=backend-repository
spring.profiles.default=dev
server.port=${SERVER_PORT:8080}
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.flyway.locations=classpath:db/migration/mysql
spring.flyway.clean-disabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true

spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:${MAIL_USERNAME:}}
spring.mail.password=${MAIL_PASS:${MAIL_PASSWORD:}}
app.mobile-base-url=${APP_MOBILE_BASE_URL:http://localhost:5173/mobile}
app.entry-base-url=${APP_ENTRY_BASE_URL:http://localhost:5173/entry}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
