spring.application.name=backend-repository
spring.profiles.default=dev
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8080}
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.flyway.locations=classpath:db/migration/mysql
spring.flyway.clean-disabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
