create table attractions (
    available_seats integer not null,
    maintenance_frequency_days integer not null,
    total_seats integer not null,
    id bigint generated by default as identity,
    description varchar(255) not null,
    image_url varchar(255) not null,
    name varchar(255) not null,
    size varchar(255) not null,
    status varchar(255) not null,
    primary key (id)
);

create table bookings (
    email_sent boolean not null,
    total_price numeric(38,2) not null,
    visit_date date not null,
    created_at timestamp(6),
    hotel_id bigint,
    id bigint generated by default as identity,
    offer_id bigint,
    updated_at timestamp(6),
    user_id bigint not null,
    board_type varchar(255) not null,
    emails_participants varbinary(255),
    primary key (id)
);

create table employees (
    active boolean not null,
    id bigint generated by default as identity,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    dni varchar(255) not null unique,
    email varchar(255) not null unique,
    employee_type varchar(255) not null,
    shift varchar(255) not null,
    primary key (id)
);

create table hotels (
    available_places integer not null,
    available_rooms integer not null,
    full_board_price numeric(38,2) not null,
    half_board_price numeric(38,2) not null,
    total_places integer not null,
    total_rooms integer not null,
    id bigint generated by default as identity,
    description varchar(255) not null,
    image_url varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

create table internal_credentials (
    active boolean not null,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    username varchar(255) not null unique,
    role enum ('ADMIN') not null,
    primary key (id)
);

create table maintenance (
    scheduled_date date not null,
    attraction_id bigint not null,
    id bigint generated by default as identity,
    status varchar(255) not null,
    primary key (id)
);

create table maintenance_technicians (
    employee_id bigint not null,
    maintenance_id bigint not null
);

create table offers (
    included_tickets integer not null,
    total_price numeric(38,2) not null,
    hotel_id bigint not null,
    id bigint generated by default as identity,
    board_type varchar(255) not null,
    description varchar(255) not null,
    image_url varchar(255) not null,
    title varchar(255) not null,
    primary key (id)
);

create table payments (
    amount numeric(38,2) not null,
    booking_id bigint not null unique,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    payment_method varchar(255),
    transaction_reference varchar(255),
    status enum ('CANCELLED','FAILED','PAID','PENDING') not null,
    primary key (id)
);

create table shifts (
    end_date date not null,
    start_date date not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    shift varchar(255) not null,
    primary key (id)
);

create table tickets (
    price numeric(38,2) not null,
    booking_id bigint not null,
    id bigint generated by default as identity,
    age_range varchar(255) not null,
    holder_full_name varchar(255) not null,
    primary key (id)
);

create table users (
    birth_date date not null,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    dni varchar(255) not null unique,
    email varchar(255) not null unique,
    phone varchar(255),
    primary key (id)
);

alter table bookings add constraint FK7y09f5lun38jnooaw2hch0ke9 foreign key (hotel_id) references hotels;
alter table bookings add constraint FK1rpb9nchx8835ck1u3pla0t8k foreign key (offer_id) references offers;
alter table bookings add constraint FKeyog2oic85xg7hsu2je2lx3s6 foreign key (user_id) references users;
alter table maintenance add constraint FKjpl8fl7o9k4bi2qtnglu02c2y foreign key (attraction_id) references attractions;
alter table maintenance_technicians add constraint FK9jr0d1lm69okmiqch7ooaco8x foreign key (employee_id) references employees;
alter table maintenance_technicians add constraint FK806y3xepf2cf5ywwwo1iqn1bj foreign key (maintenance_id) references maintenance;
alter table offers add constraint FK9aljdqoi39d35fattfdgp95ac foreign key (hotel_id) references hotels;
alter table payments add constraint FKc52o2b1jkxttngufqp3t7jr3h foreign key (booking_id) references bookings;
alter table shifts add constraint FKtbsbc3nmr4b1vlwtnd944q9u7 foreign key (employee_id) references employees;
alter table tickets add constraint FKefja4avuu7g29t78mxifrsynb foreign key (booking_id) references bookings;
